### ISSUE TITLE
What do they do?

### ISSUE THREAD

**Issue by ukmoose** [esdkrwl/IoT2School#4]
Many thanks for creating the nodes. I understand the main reason for creating them is for you thesis but it would be useful if your readme also said what the nodes do. Could you add a brief description of what each of the nodes actually does? Many thanks

**Comment by esdkrwl** [comment]
It's on my todo list. 
I already added a brief german description within node-red. But I can not recommend using the nodes without an online documentation yet, because you need a specific firmware and the python3 script "saymyname.py" running on your mashine in order to utilize them.

**Comment by esdkrwl** [comment]
Added brief decription:
https://www.npmjs.com/package/node-red-contrib-iot4school
